#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

if [[ -z "${VALUE_CHECKPOINT:-}" && -n "${VALUE_OUTPUT:-}" ]]; then
    VALUE_CHECKPOINT="${VALUE_OUTPUT}/pi05_value_final.pt"
fi

require_vars SFT_POLICY_CHECKPOINT NORM_STATS DEMO_DATASET POSITIVE_DATASET
require_vars FAILURE_DATASET NEW_ROLLOUT_DATASET VALUE_CHECKPOINT POSITIVE_POLICY_CHECKPOINT

RUN_ID="${RUN_ID:-$(date +%Y%m%d_%H%M%S)}"
FINAL_POLICY_OUTPUT="${FINAL_POLICY_OUTPUT:-${ARTIFACT_ROOT}/value_conditioned_policy_${RUN_ID}}"
VALUE_LABEL_REPORT="${VALUE_LABEL_REPORT:-${ARTIFACT_ROOT}/value_labels_${RUN_ID}.json}"
FINAL_CONFIG="${FINAL_CONFIG:-${WORKFLOW_ROOT}/generated/value_conditioned_vla_${RUN_ID}.yaml}"
FINAL_POLICY_STEPS="${FINAL_POLICY_STEPS:-5000}"
POLICY_BATCH_SIZE="${POLICY_BATCH_SIZE:-8}"
POLICY_NUM_WORKERS="${POLICY_NUM_WORKERS:-4}"
POLICY_WARMUP_STEPS="${POLICY_WARMUP_STEPS:-1000}"
VALUE_INFERENCE_BATCH_SIZE="${VALUE_INFERENCE_BATCH_SIZE:-128}"
VALUE_INFERENCE_WORKERS="${VALUE_INFERENCE_WORKERS:-4}"
ADVANTAGE_POSITIVE_FRACTION="${ADVANTAGE_POSITIVE_FRACTION:-0.30}"

DEMO_EPISODES="$(dataset_episodes "${DEMO_DATASET}")"
POLICY_SUCCESS_EPISODES="$(json_field "${POSITIVE_DATASET}/positive_export.json" policy_success_episodes)"
FAILURE_EPISODES="$(dataset_episodes "${FAILURE_DATASET}")"
NEW_ROLLOUT_EPISODES="$(dataset_episodes "${NEW_ROLLOUT_DATASET}")"
TOTAL_EPISODES=$((DEMO_EPISODES + POLICY_SUCCESS_EPISODES + FAILURE_EPISODES + NEW_ROLLOUT_EPISODES))
if [[ -z "${GLOBAL_RETURN_MIN:-}" ]]; then
    require_vars VALUE_OUTPUT
    GLOBAL_RETURN_MIN="$(json_field "${VALUE_OUTPUT}/training_summary.json" global_return_min)"
fi

export VALUE_CHECKPOINT FINAL_POLICY_OUTPUT VALUE_LABEL_REPORT FINAL_POLICY_STEPS
export POLICY_BATCH_SIZE POLICY_NUM_WORKERS POLICY_WARMUP_STEPS
export VALUE_INFERENCE_BATCH_SIZE VALUE_INFERENCE_WORKERS ADVANTAGE_POSITIVE_FRACTION
export DEMO_EPISODES POLICY_SUCCESS_EPISODES FAILURE_EPISODES NEW_ROLLOUT_EPISODES
export TOTAL_EPISODES GLOBAL_RETURN_MIN
export SFT_POLICY_CHECKPOINT POSITIVE_POLICY_CHECKPOINT NORM_STATS
export DEMO_DATASET POSITIVE_DATASET FAILURE_DATASET NEW_ROLLOUT_DATASET

render_config "${WORKFLOW_ROOT}/configs/value_conditioned_vla.yaml.in" "${FINAL_CONFIG}"

RECAP_DIR="${RLINF_ROOT}/examples/offline_rl/piperx_recap_edited"
cd "${RECAP_DIR}"
"${RLINF_PYTHON}" -u label_value_advantages_edited.py --config "${FINAL_CONFIG}"
"${RLINF_PYTHON}" -u train_value_conditioned_policy_edited.py --config "${FINAL_CONFIG}"

printf 'VALUE_LABEL_REPORT=%s\nFINAL_POLICY_OUTPUT=%s\nFINAL_POLICY_CHECKPOINT=%s\n' \
  "${VALUE_LABEL_REPORT}" "${FINAL_POLICY_OUTPUT}" \
  "${FINAL_POLICY_OUTPUT}/checkpoints/global_step_${FINAL_POLICY_STEPS}/actor"
